# Generated by Django 5.1.2 on 2024-10-25 15:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sorting', models.IntegerField()),
                ('layer_name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='layers/files/')),
                ('coordinate_system', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('properties', models.JSONField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('fk_layers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='service.layer')),
            ],
        ),
    ]
