# Generated by Django 5.1.2 on 2024-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='original_file',
            field=models.FileField(upload_to='media/layers/files/'),
        ),
    ]
